@startuml

title __REGRESSION's Class Diagram__\n

  namespace testsuite {
    namespace regression {
      class testsuite.regression.BlobRegressionTest {
          + testBug10850()
          + testBug20453671()
          + testBug20453712()
          + testBug23535571()
          + testBug2670()
          + testBug34677()
          + testBug5490()
          + testBug8096()
          + testBug9040()
          + testBug95210()
          + testUpdatableBlobsWithCharsets()
          + testUpdateLongBlobGT16M()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.CachedRowsetTest {
          + testBug5188()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.CallableStatementRegressionTest {
          + testBitSp()
          + testBug10310()
          + testBug111107()
          + testBug115265()
          + testBug12417()
          + testBug15121()
          + testBug15464()
          + testBug17898()
          + testBug19857166()
          + testBug20279641()
          + testBug21462()
          + testBug22024()
          + testBug22297()
          + testBug25379()
          + testBug25715()
          + testBug26143()
          + testBug26259384()
          + testBug26959()
          + testBug27400()
          + testBug28689()
          + testBug31823()
          + testBug35199()
          + testBug3539()
          + testBug3540()
          + testBug36936407()
          + testBug38954()
          + testBug43576()
          + testBug49831()
          + testBug57022()
          + testBug60816()
          + testBug7026()
          + testBug73774()
          + testBug79561()
          + testBug84324()
          + testBug87704()
          + testBug9319()
          + testBug95796()
          + testBug9682()
          + testHugeNumberOfParameters()
          + testNotReallyCallableStatement()
          + testPrepareOfMultiRs()
          - execProcBug49831()
          - testBug115265RunTest()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.CharsetRegressionTest {
          + testAsciiCharConversion()
          + testBug100606()
          + testBug10496()
          + testBug12752()
          + testBug15544()
          + testBug24840()
          + testBug25504578()
          + testBug25554464_1()
          + testBug25554464_2()
          + testBug34090350()
          + testBug37931()
          + testBug41730()
          + testBug64205()
          + testBug71038()
          + testBug72630()
          + testBug72712()
          + testBug73663()
          + testBug7607()
          + testBug81196()
          + testBug91317()
          + testBug9206()
          + testBug95139()
          + testEncodingRegression()
          + testEscapeSJISDoubleEscapeBug()
          + testGreekUtf8411()
          + testPasswordCharacterEncoding()
          - checkCollationConnection()
          - testBug95139CheckVariables()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.CharsetRegressionTest.Bug71038QueryInterceptor {
          ~ cnt : int
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.CharsetRegressionTest.Bug72712QueryInterceptor {
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.CharsetRegressionTest.Bug73663QueryInterceptor {
          + preProcess()
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.CharsetRegressionTest.Bug95139QueryInterceptor {
          ~ queryVarsCnt : int
          ~ setCharacterSetResultsCnt : int
          ~ setCharacterSetResultsQuery : String
          ~ setNamesCnt : int
          ~ setNamesQuery : String
          + preProcess()
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.CharsetRegressionTest.TestBug64205QueryInterceptor {
          - connection : JdbcConnection
          + init()
          + postProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.CharsetRegressionTest.TestSetNamesQueryInterceptor {
          {static} + query : String
          {static} + usedSetNames : boolean
          + init()
          + preProcess()
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest {
          # testServerPrepStmtDeadlockCounter : int
          ~ testBug75615Future : Future<?>
          {static} + containsMessage()
          + testAuthCleartextPlugin()
          + testAuthTestPlugin()
          + testAutoCommitLB()
          + testBug10144()
          + testBug101596()
          + testBug102188()
          + testBug102404()
          + testBug104067AndBug106435()
          + testBug11237()
          + testBug11259()
          + testBug11879()
          + testBug11976()
          + testBug12218()
          + testBug12229()
          + testBug12753()
          + testBug13048()
          + testBug13453()
          + testBug14563127()
          + testBug15065()
          + testBug15570()
          + testBug16224249()
          + testBug16634180()
          + testBug17251955()
          + testBug18869381()
          + testBug1914()
          + testBug19354014()
          + testBug20685022()
          + testBug20825727()
          + testBug21286268()
          + testBug21789378()
          + testBug21934573()
          + testBug21947042()
          + testBug22508715()
          + testBug22643()
          + testBug22678872()
          + testBug22730682()
          + testBug22848249()
          + testBug23143279()
          + testBug23281()
          + testBug23626()
          + testBug24706()
          + testBug25514()
          + testBug25545()
          + testBug25642021()
          + testBug25642226()
          + testBug25701740()
          + testBug26089880()
          + testBug26819691()
          + testBug27102307()
          + testBug27131768()
          + testBug27655()
          + testBug28150662()
          + testBug28725534()
          + testBug29329326()
          + testBug29852()
          + testBug31053()
          + testBug32216()
          + testBug32877()
          + testBug33734()
          + testBug34703()
          + testBug34937()
          + testBug3554()
          + testBug35660()
          + testBug36662()
          + testBug36948()
          + testBug37570()
          + testBug3790()
          + testBug41172()
          + testBug4334()
          + testBug43421()
          + testBug44324()
          + testBug44587()
          + testBug45171()
          + testBug45419()
          + testBug46637()
          + testBug46925()
          + testBug47494()
          + testBug48442()
          + testBug48486()
          + testBug48605()
          + testBug49700()
          + testBug51266()
          + testBug51643()
          + testBug51783()
          + testBug56100()
          + testBug56122()
          + testBug56429()
          + testBug56955()
          + testBug57662()
          + testBug58706()
          + testBug61201()
          + testBug62452()
          + testBug62577()
          + testBug63284()
          + testBug67803()
          + testBug68400()
          + testBug68733()
          + testBug68763()
          + testBug69452()
          + testBug69506()
          + testBug69579()
          + testBug6966()
          + testBug69746()
          + testBug69777()
          + testBug70677()
          + testBug70785()
          + testBug71084()
          + testBug71850()
          + testBug73053()
          + testBug74690()
          + testBug74711()
          + testBug75168()
          + testBug75209()
          + testBug75592()
          + testBug75615()
          + testBug75670()
          + testBug77171()
          + testBug77649()
          + testBug7952()
          + testBug79612()
          + testBug86741()
          + testBug87600()
          + testBug88227()
          + testBug88232()
          + testBug88242()
          + testBug89948()
          + testBug90753()
          + testBug91421()
          + testBug92625()
          + testBug93007()
          + testBug95564()
          + testBug97714()
          + testBug98445()
          + testBug98667()
          + testBug99076()
          + testBug99767()
          + testCachingSha2PasswordPlugin()
          + testChangeUser()
          + testChangeUserClosedConn()
          + testChangeUserNoDb()
          + testDefaultPlugin()
          + testDefaultUserWithPasswordAuthentication()
          + testDefaultUserWithoutPasswordAuthentication()
          + testDisabledPlugins()
          + testEnableTLSVersion()
          + testExpiredPassword()
          + testFailoverReadOnly()
          + testIsLocal()
          + testLongAuthResponsePayload()
          + testOldPasswordPlugin()
          + testPropertiesDescriptionsKeys()
          + testReconnectWithCachedConfig()
          + testReplicationConnectWithMultipleSources()
          + testReplicationConnectWithNoSource()
          + testReplicationConnectionGroupHostManagement()
          + testReplicationConnectionHostManagement()
          + testReplicationConnectionMemory()
          + testReplicationConnectionNoReplicasBasics()
          + testReplicationConnectionNoReplicasRemainOnSource()
          + testReplicationJMXInterfaces()
          + testSetReadOnly()
          + testSha256PasswordPlugin()
          + testStackOverflowOnMissingInterceptor()
          + testStatementComment()
          + testTLSVersion()
          + testThreeAttemptsPlugin()
          + testTwoQuestionsPlugin()
          + testUnreliableSocketFactory()
          ~ testBug108643()
          ~ testBug109013()
          ~ testBug114705()
          ~ testBug114989()
          ~ testBug34918989()
          ~ testBug35358417()
          - allowsRsa()
          - assertCurrentUser()
          - checkBug32216()
          - checkPingQuery()
          - countTestConnections()
          - findNamedThreadCount()
          - getReplicationMBean()
          - getTestReplicationConnectionNoReplicas()
          - isResultSetClosedForTestBug69746()
          - isStatementClosedForTestBug69746()
          {static} - killConnection()
          - subTestBug22848249A()
          - subTestBug22848249B()
          - subTestBug22848249C()
          - subTestBug22848249D()
          - testBug18869381WithProperties()
          - testBug20825727ChangePassword()
          - testBug20825727CreateUser()
          - testBug20825727TestLogin()
          - testBug21286268AssertConnectedToAndReadOnly()
          - testBug21947042_PrintCipher()
          - testBug21947042_PrintVersion()
          - testBug22678872CheckConnectionsHistory()
          - testBug23143279RunTest()
          - testBug23626ForClass()
          - testBug56100AssertHost()
          - testBug62452WithConnection()
          - testBug62577TestUrl()
          - testBug71084AssertCase()
          - testBug89948Check()
          - testConnectionAttributes()
          - testMemLeakBatch()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.AuthTestPlugin {
          - password : String
          + destroy()
          + getProtocolPluginName()
          + isReusable()
          + nextAuthenticationStep()
          + requiresConfidentiality()
          + reset()
          + setAuthenticationParameters()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.Bug104067QueryInterceptor {
          {static} + errorOnSetTrue : boolean
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.Bug29329326QueryInterceptor {
          ~ cnt : int
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.Bug56100QueryInterceptor {
          - connection : JdbcConnection
          + destroy()
          + init()
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.Bug75168LoadBalanceExceptionChecker {
          + destroy()
          + init()
          + shouldExceptionTriggerFailover()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.Bug75168QueryInterceptor {
          {static} ~ previousConnection : Connection
          - connection : JdbcConnection
          + destroy()
          + init()
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.Bug75592QueryInterceptor {
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.Bug88227QueryInterceptor {
          {static} + enabled : boolean
          + postProcess()
          + preProcess()
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.CancelTask {
          - c : Connection
          - num : int
          + run()
          ~ CancelTask()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.CountingReBalanceStrategy {
          {static} - rebalancedTimes : int
          {static} + getTimesRebalanced()
          + pickConnection()
          {static} + resetTimesRebalanced()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.ForcedLoadBalanceStrategy {
          {static} - forceFutureServerTimes : int
          {static} - forcedFutureServer : String
          {static} + dontForceFutureServer()
          {static} + forceFutureServer()
          + pickConnection()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.PollTask {
          - c : Connection
          - num : int
          - pst1 : PreparedStatement
          - st1 : Statement
          + run()
          ~ PollTask()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.PortNumberSocketFactory {
          + connect()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.TestBug101596Transformer {
          + transformProperties()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.TestBug102404Listener {
          ~ changes : ServerSessionStateChanges
          + handleSessionStateChanges()
          - printChange()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.TestBug21934573ExceptionInterceptor {
          {static} ~ initialized : boolean
          {static} ~ mainThreadLock : Object
          {static} - replConnGroupLocks : Set<String>
          {static} - threadIsWaiting : boolean
          - useSyncGroupServersLock : boolean
          + destroy()
          + init()
          + interceptException()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.TestBug34918989PropTransKO {
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.TestBug34918989PropTransOK {
          + transformProperties()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.TestBug35358417Listener {
          ~ capturedChanges : ServerSessionStateChanges
          + handleSessionStateChanges()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.TestBug57662Logger {
          + hasNegativeDurations : boolean
          + TestBug57662Logger()
          # logInternal()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.TestBug67803ExceptionInterceptor {
          + destroy()
          + init()
          + interceptException()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.TestBug71850ExceptionInterceptor {
          - counter : int
          + destroy()
          + init()
          + interceptException()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.TestBug73053InputStreamWrapper {
          ~ loopCount : int
          ~ underlyingInputStream : InputStream
          + TestBug73053InputStreamWrapper()
          + available()
          + close()
          + equals()
          + hashCode()
          + mark()
          + markSupported()
          + read()
          + read()
          + read()
          + reset()
          + skip()
          + toString()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.TestBug73053SocketFactory {
          + connect()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.TestBug73053SocketWrapper {
          ~ underlyingSocket : Socket
          + TestBug73053SocketWrapper()
          + bind()
          + close()
          + connect()
          + connect()
          + equals()
          + getChannel()
          + getInetAddress()
          + getInputStream()
          + getKeepAlive()
          + getLocalAddress()
          + getLocalPort()
          + getLocalSocketAddress()
          + getOOBInline()
          + getOutputStream()
          + getPort()
          + getReceiveBufferSize()
          + getRemoteSocketAddress()
          + getReuseAddress()
          + getSendBufferSize()
          + getSoLinger()
          + getSoTimeout()
          + getTcpNoDelay()
          + getTrafficClass()
          + hashCode()
          + isBound()
          + isClosed()
          + isConnected()
          + isInputShutdown()
          + isOutputShutdown()
          + sendUrgentData()
          + setKeepAlive()
          + setOOBInline()
          + setPerformancePreferences()
          + setReceiveBufferSize()
          + setReuseAddress()
          + setSendBufferSize()
          + setSoLinger()
          + setSoTimeout()
          + setTcpNoDelay()
          + setTrafficClass()
          + shutdownInput()
          + shutdownOutput()
          + toString()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.TestBug98445ClientInfoProvider {
          + destroy()
          + getClientInfo()
          + getClientInfo()
          + initialize()
          + setClientInfo()
          + setClientInfo()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.ThreadPerTaskExecutor {
          + execute()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.ThreeAttemptsPlugin {
          - counter : int
          - password : String
          + destroy()
          + getProtocolPluginName()
          + isReusable()
          + nextAuthenticationStep()
          + requiresConfidentiality()
          + reset()
          + setAuthenticationParameters()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ConnectionRegressionTest.TwoQuestionsPlugin {
          - password : String
          + destroy()
          + getProtocolPluginName()
          + isReusable()
          + nextAuthenticationStep()
          + requiresConfidentiality()
          + reset()
          + setAuthenticationParameters()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.DataSourceRegressionTest {
          - ctx : Context
          + setUp()
          + tearDown()
          + testBug104954()
          + testBug16791()
          + testBug19169()
          + testBug32101()
          + testBug35810()
          + testBug3848()
          + testBug3920()
          + testBug42267()
          + testBug4808()
          + testBug72632()
          + testBug72890()
          + testBug91351()
          + testCSC4616()
          - bindDataSource()
          - lookupDatasourceInJNDI()
          - removeFromRef()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.DateTimeRegressionTest {
          + testBug101413()
          + testBug104559()
          + testBug15604()
          + testBug20316640()
          + testBug20391832()
          + testBug20818678()
          + testBug21308907()
          + testBug22305930()
          + testBug3620()
          + testBug5874()
          - subTestBug20391832()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.EscapeProcessorRegressionTest {
          + testBug11498()
          + testBug11797()
          + testBug14909()
          + testBug19845752()
          + testBug25399()
          + testBug60598()
          + testBug63526()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ExceptionSubclassesTest {
          + testBug17750877()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.MetaDataRegressionTest {
          + testABunchOfReturnTypes()
          + testBug102076()
          + testBug104641()
          + testBug106758()
          + testBug113600()
          + testBug11575()
          + testBug11781()
          + testBug12970()
          + testBug12975()
          + testBug13277()
          + testBug13601()
          + testBug14815()
          + testBug15854()
          + testBug16277()
          + testBug16436511()
          + testBug17248345()
          + testBug18258()
          + testBug18554()
          + testBug19803348()
          + testBug20491()
          + testBug20504139()
          + testBug20727196()
          + testBug21215151()
          + testBug21267()
          + testBug21544()
          + testBug21978216()
          + testBug22613()
          + testBug22628()
          + testBug23212347()
          + testBug23303()
          + testBug23304()
          + testBug25624()
          + testBug2607()
          + testBug27867()
          + testBug27915()
          + testBug27916()
          + testBug2852()
          + testBug2855()
          + testBug29186870()
          + testBug31187()
          + testBug33594()
          + testBug33723611()
          + testBug34194()
          + testBug35115()
          + testBug3570()
          + testBug38367()
          + testBug41269()
          + testBug4138()
          + testBug43714()
          + testBug44451()
          + testBug44508()
          + testBug4742()
          + testBug4860()
          + testBug4880()
          + testBug51912()
          + testBug52167()
          + testBug57808()
          + testBug61150()
          + testBug61203()
          + testBug61332()
          + testBug63456()
          + testBug63800()
          + testBug6399()
          + testBug65871()
          + testBug68098()
          + testBug68307()
          + testBug69290()
          + testBug69298()
          + testBug7033()
          + testBug7081()
          + testBug73775()
          + testBug76187()
          + testBug82084()
          + testBug87826()
          + testBug8792()
          + testBug8800()
          + testBug8803()
          + testBug8812()
          + testBug90887()
          + testBug9320()
          + testBug95280()
          + testBug97413()
          + testBug9769()
          + testBug9778()
          + testBug9917()
          + testCharVarchar()
          + testCharacterSetForDBMD()
          + testFixForBug1673()
          + testGetColumns()
          + testGetColumnsBug1099()
          + testGetColumnsUnsigned()
          + testGetPropertyInfo()
          + testIsCaseSensitive()
          + testLongText()
          + testNoSystemTablesReturned()
          + testQuotedGunk()
          + testRSMDToStringFromDBMD()
          + testSupportesGroupByUnrelated()
          + testSupportsCorrelatedSubqueries()
          + testTypes()
          ~ testBug109807()
          ~ testBug109808()
          ~ testBug91550()
          ~ testBug96582()
          - callFunction()
          - callProcedure()
          - checkABunchOfReturnTypesForConnection()
          - checkBug27915()
          - checkFunctionColumnTypeForBug68307()
          - checkGetFunctionColumnsForBug69298()
          - checkGetFunctionsForBug69298()
          - checkGetProcedureColumnsForBug69298()
          - checkGetProceduresForBug69298()
          - checkMetaDataInfoForBug17248345()
          - checkMetadataForBug22613()
          - checkProcedureColumnTypeForBug68307()
          - checkReturnedColumnsForBug44451()
          - checkRsmdForBug13277()
          - checkTypes()
          - compareResultSets()
          - testAbsenceOfMetadataForQuery()
          - testBug18554()
          - testBug61203checks()
          - testBug65871_testCatalog()
          - testBug65871_testCatalogs()
          - testBug65871_testTable()
          - testDatetime()
          - testTimestamp()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.MetaDataRegressionTest.QueryInterceptorBug61332 {
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.MetaDataRegressionTest.TestBug97413Columns {
          ~ decimalField : String
          ~ errMsg : String
          ~ id : int
          ~ pm : ParameterMetaData
          ~ precisionField : String
          ~ rm : ResultSetMetaData
          ~ rset : ResultSet
          ~ tidField : String
          ~ tinyInt1isBit : boolean
          ~ tnField : String
          ~ transformedBitIsBoolean : boolean
          ~ widthField : String
          ~ TestBug97413Columns()
          ~ TestBug97413Columns()
          ~ TestBug97413Columns()
          ~ run()
          ~ testBug97413CheckMDColumn()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.MicroPerformanceRegressionTest {
          {static} - BASELINE_TIMES : Map<String, Double>
          {static} - LEEWAY : double
          {static} - ORIGINAL_LOOP_TIME_MS : double
          {static} - scaleFactor : double
          {static} - scaleFactorSamples : double[]
          + setUp()
          + testBug6359()
          + testPreparedStatementTimes()
          + testResultSetAccessors()
          {static} - adjustScaleFactor()
          {static} - calculateScaleFactor()
          - checkTime()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.NonLocalSocketFactory {
          + isLocallyConnected()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.NumbersRegressionTest {
          + testBigInt()
          + testBug105915()
          + testBug5729()
          + testBug8484()
          + testFloatsAndReals()
          + testIntShouldReturnLong()
          + testPrecisionAndScale()
          - testPrecisionForType()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.PooledConnectionRegressionTest {
          # closeEventCount : int
          # connectionErrorEventCount : int
          - cpds : ConnectionPoolDataSource
          + setUp()
          + tearDown()
          + testBug35489()
          + testBug7136()
          + testCloseEvent()
          + testConnectionReclaim()
          + testConnectionWrapperMethods()
          + testPacketTooLargeException()
          - checkConnectionReturnedToPool()
          - checkReallyClosedConnection()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.PooledConnectionRegressionTest.ConnectionListener {
          + connectionClosed()
          + connectionErrorOccurred()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ResultSetRegressionTest {
          + testAllTypesForNull()
          + testBogusTimestampAsString()
          + testBooleans()
          + testBug10156()
          + testBug10212()
          + testBug102131()
          + testBug102321()
          + testBug10485()
          + testBug105197()
          + testBug11190()
          + testBug11552()
          + testBug12104()
          + testBug14562()
          + testBug14609()
          + testBug14897()
          + testBug15677()
          + testBug1592()
          + testBug16169()
          + testBug16841()
          + testBug17450()
          + testBug18880()
          + testBug19282()
          + testBug19536760()
          + testBug19568()
          + testBug19724()
          + testBug19805370()
          + testBug2006()
          + testBug20306()
          + testBug20391631()
          + testBug20391659()
          + testBug20479()
          + testBug20485()
          + testBug20802947()
          + testBug20804635()
          + testBug20913289()
          + testBug21062()
          + testBug21379()
          + testBug21814()
          + testBug22305979()
          + testBug22931433()
          + testBug23197238()
          + testBug2359()
          + testBug23702040()
          + testBug24525461()
          + testBug24527173()
          + testBug24710()
          + testBug24886()
          + testBug25215008()
          + testBug25328()
          + testBug25517()
          + testBug25650305()
          + testBug25650385()
          + testBug25650482()
          + testBug25650514()
          + testBug25787()
          + testBug25894()
          + testBug26173()
          + testBug2623()
          + testBug26266731()
          + testBug2654()
          + testBug26750705()
          + testBug26789()
          + testBug27317()
          + testBug27431()
          + testBug27784363()
          + testBug28085()
          + testBug30474158()
          + testBug30664()
          + testBug30851()
          + testBug31747910()
          + testBug32525()
          + testBug32954396()
          + testBug33162()
          + testBug33185116()
          + testBug33678()
          + testBug34762()
          + testBug34913()
          + testBug35610()
          + testBug36051()
          + testBug38252()
          + testBug38387()
          + testBug39911()
          + testBug41484()
          + testBug41484_2()
          + testBug43759()
          + testBug4482()
          + testBug45757()
          + testBug4689()
          + testBug48820()
          + testBug49516()
          + testBug49797()
          + testBug5032()
          + testBug5069()
          + testBug5136()
          + testBug56479()
          + testBug5664()
          + testBug5717()
          + testBug60313()
          + testBug6231()
          + testBug64204()
          + testBug6537()
          + testBug65503()
          + testBug6561()
          + testBug6619()
          + testBug67318()
          + testBug6743()
          + testBug68608()
          + testBug70704()
          + testBug72000()
          + testBug72023()
          + testBug72609()
          + testBug75309()
          + testBug7686()
          + testBug7715()
          + testBug78685()
          + testBug80441()
          + testBug80522()
          + testBug80532()
          + testBug80631()
          + testBug81202()
          + testBug82707()
          + testBug82964()
          + testBug83368()
          + testBug83662()
          + testBug84189()
          + testBug8428()
          + testBug85941()
          + testBug8868()
          + testBug9098()
          + testBug91065()
          + testBug9236()
          + testBug92536()
          + testBug9437()
          + testBug94457()
          + testBug94533()
          + testBug94585()
          + testBug96059()
          + testBug96383()
          + testBug9684()
          + testBug97724()
          + testBug97757()
          + testBug99013()
          + testClobTruncate()
          + testClobberStreamingRS()
          + testEmptyResultSetGet()
          + testEmptyStringsWithNumericGetters()
          + testGetLongBug()
          + testGetTimestampWithDate()
          + testIsBeforeFirstOnEmpty()
          + testMetaDataIsWritable()
          + testNPEWithStatementsAndTime()
          + testNPEWithUsageAdvisor()
          + testNextAndPrevious()
          + testNotUpdatable()
          + testRanges()
          + testStreamingRegBug()
          + testTruncationDisable()
          + testTruncationOfNonSigDigits()
          + testUpdatability()
          + testUpdatabilityAndEscaping()
          + testUpdatabilityWithQuotes()
          + testUpdateClob()
          + testUsageAdvisorOnZeroRowResultSet()
          ~ testBug102678()
          ~ testBug107215()
          ~ testBug108830()
          ~ testBug110586()
          ~ testBug113129()
          - checkBug20306()
          - checkEmptyConvertToZero()
          - checkEmptyConvertToZeroException()
          - checkRangeMatrix()
          - checkRanges()
          - checkResult17450()
          - checkResultsBug19568()
          - checkTimestampNanos()
          - checkUpdatabilityMessage()
          - exercise35610()
          - exerciseUpdatableResultSet()
          - testAllFieldsForNotNull()
          - testAllFieldsForNull()
          - testBug19536760CheckStates()
          - testBug23197238AssertDoc()
          - testBug23197238AssertId()
          - testBug24527173Results()
          - testBug78685CheckData()
          - traverseResultSetBug14562()
          - tstBug24525461assertResults1()
          - tstBug24525461assertResults2()
          - tstBug24525461testBytes()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.ResultSetRegressionTest.TestBug67318ExceptionInterceptor {
          + alreadyClosedCounter : int
          + destroy()
          + init()
          + interceptException()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest {
          # testServerPrepStmtDeadlockCounter : int
          {static} ~ count : int
          {static} ~ nextID : int
          {static} ~ tests : int[][]
          + testBlobWithSJIS()
          + testBug101054()
          + testBug101242()
          + testBug101389()
          + testBug10155()
          + testBug101558()
          + testBug103303()
          + testBug103612()
          + testBug103796()
          + testBug103878()
          + testBug104349()
          + testBug104753()
          + testBug105211()
          + testBug106240()
          + testBug106252()
          + testBug10630()
          + testBug107222()
          + testBug108195()
          + testBug108414()
          + testBug108419()
          + testBug109243()
          + testBug109418()
          + testBug109864()
          + testBug11115()
          + testBug112790()
          + testBug11540()
          + testBug116114()
          + testBug11663()
          + testBug11798()
          + testBug13255()
          + testBug15024()
          + testBug15141()
          + testBug15383()
          + testBug17099()
          + testBug17587()
          + testBug1774()
          + testBug18041()
          + testBug18091639()
          + testBug1901()
          + testBug1933()
          + testBug1934()
          + testBug1958()
          + testBug19615()
          + testBug20029()
          + testBug20391550()
          + testBug20453773()
          + testBug20650()
          + testBug20687()
          + testBug20888()
          + testBug21132376()
          + testBug21207()
          + testBug21438()
          + testBug21876798()
          + testBug21978230()
          + testBug22290()
          + testBug22359()
          + testBug22931632()
          + testBug22931700()
          + testBug23188498()
          + testBug23201930()
          + testBug23204652()
          + testBug24344()
          + testBug24360()
          + testBug25009()
          + testBug25025()
          + testBug25073()
          + testBug2606()
          + testBug2671()
          + testBug26748909()
          + testBug26995710()
          + testBug27412()
          + testBug27453692()
          + testBug28256()
          + testBug28469()
          + testBug28596()
          + testBug28851()
          + testBug30508()
          + testBug30550()
          + testBug3103()
          + testBug31193()
          + testBug32577()
          + testBug33823()
          + testBug34093()
          + testBug34093_nonbatch()
          + testBug34185()
          + testBug34518()
          + testBug34555()
          + testBug35170()
          + testBug3520()
          + testBug3557()
          + testBug35653()
          + testBug35666()
          + testBug3620new()
          + testBug36478()
          + testBug3697()
          + testBug37458()
          + testBug3804()
          + testBug3873()
          + testBug38747()
          + testBug39352()
          + testBug39426()
          + testBug39956()
          + testBug40279()
          + testBug40439()
          + testBug41161()
          + testBug4119()
          + testBug41448()
          + testBug41532()
          + testBug41566()
          + testBug42253()
          + testBug4311()
          + testBug43196()
          + testBug44056()
          + testBug4510()
          + testBug46788()
          + testBug4718()
          + testBug48172()
          + testBug5012()
          + testBug50348()
          + testBug5133()
          + testBug51666()
          + testBug51704()
          + testBug51776()
          + testBug5191()
          + testBug5235()
          + testBug54175()
          + testBug5450()
          + testBug5510()
          + testBug55340()
          + testBug58728()
          + testBug61501()
          + testBug62006()
          + testBug64805()
          + testBug66430()
          + testBug66947()
          + testBug6823()
          + testBug68562()
          + testBug68916()
          + testBug71131()
          + testBug71396()
          + testBug71672()
          + testBug71923()
          + testBug71929()
          + testBug73163()
          + testBug7461()
          + testBug74932()
          + testBug74998()
          + testBug75956()
          + testBug76623()
          + testBug77183()
          + testBug77368()
          + testBug77449()
          + testBug77681()
          + testBug78313()
          + testBug78961()
          + testBug80615()
          + testBug81063()
          + testBug81468()
          + testBug81706()
          + testBug8181()
          + testBug84117()
          + testBug84365()
          + testBug84783()
          + testBug84813()
          + testBug8487()
          + testBug85223()
          + testBug85317()
          + testBug87429()
          + testBug87534()
          + testBug91112()
          + testBug91112CheckResultBerlin()
          + testBug91112CheckResultMSK()
          + testBug96442()
          + testBug96623()
          + testBug96900()
          + testBug9704()
          + testBug98237()
          + testBug98536()
          + testBug98695()
          + testBug99260()
          + testBug99604()
          + testBug99713()
          + testBugDupeKeySingle()
          + testBustedGGKColumnNames()
          + testBustedGGKWithPSExecute()
          + testClientPreparedSetBoolean()
          + testCloseTwice()
          + testCommentParsing()
          + testDeadlockBatchBehavior()
          + testExecutionPlanForSlowQueries()
          + testGetGeneratedKeysAllCases()
          + testLancesBitMappingBug()
          + testLikeWithBackslashes()
          + testLimitAndMaxRows()
          + testLoadData()
          + testMoreLanceBugs()
          + testNullClob()
          + testPStmtTypesBug()
          + testParameterBoundsCheck()
          + testReversalOfScanFlags()
          + testServerPrepStmtAndDate()
          + testServerPrepStmtDeadlock()
          + testSetCharacterStream()
          + testSetFetchSize()
          + testSetMaxRows()
          + testTimestampNPE()
          + testTruncationWithChar()
          + testUpdatableStream()
          + testbug12565726()
          + testbug61866()
          ~ testBug102520()
          ~ testBug107107()
          ~ testBug107577()
          ~ testBug108415()
          ~ testBug109377()
          ~ testBug109546()
          ~ testBug110321()
          ~ testBug112195()
          ~ testBug112884()
          ~ testBug113509()
          ~ testBug34558945()
          - addBatchItems()
          - checkBug34093()
          - checkOpenResultsFor44056()
          - checkPreparedStatementForTestBug50348()
          - checkPreparedStatementForTestBug71672()
          - checkResultSetForTestBug50348()
          - checkStatementForTestBug71672()
          - createGGKTables()
          - doGGKTestPreparedStatement()
          - doGGKTestStatement()
          - dropGGKTables()
          - execQueryBug5191()
          - innerBug6823()
          - subTestBug68916ForAllowMultiQueries()
          - subTestBug68916ForConcurrency()
          - subTestBug68916ForDontTrackOpenResources()
          - subTestBug68916ForHoldResultsOpenOverStatementClose()
          - subTestBug68916ForStandardConnection()
          - testBug68562BatchWithSize()
          - testBug68562ExecuteBatch()
          - testBug71396MultiSettingsCheck()
          - testBug71396PrepStatementCheck()
          - testBug71396PrepStatementCheck()
          - testBug71396PrepStatementClose()
          - testBug71396PrepStatementInit()
          - testBug71396PrepStatementMultiCheck()
          - testBug71396PrepStatementMultiCheck()
          - testBug71396StatementCheck()
          - testBug71396StatementInit()
          - testBug71396StatementMultiCheck()
          - testBug71396StatementMultiCheck()
          - testBug74932ExecuteStmts()
          - testBug80615CheckComStmtStatus()
          - testBug81063CheckAndReset()
          - testBug84813CheckAndReset()
          - testStreamsForBug15024()
          - timeBatch()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest.Bug101389QueryInterceptor {
          {static} + enabled : boolean
          + preProcess()
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest.Bug39426Interceptor {
          {static} + vals : List<Integer>
          ~ prevSql : String
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest.IsClosedInputStream {
          ~ isClosed : boolean
          + IsClosedInputStream()
          + IsClosedInputStream()
          + close()
          + isClosed()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest.IsClosedReader {
          ~ isClosed : boolean
          + IsClosedReader()
          + close()
          + isClosed()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest.PrepareThread {
          ~ c : Connection
          + run()
          ~ PrepareThread()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest.QueryInfoQueryInterceptor {
          {static} - capturedSql : List<String>
          {static} - enabled : boolean
          {static} + assertCapturedSql()
          + preProcess()
          {static} + startCapturing()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest.ScanDetectingInterceptor {
          {static} ~ hasSeenBadIndex : boolean
          {static} ~ hasSeenScan : boolean
          + postProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest.TestBug51666QueryInterceptor {
          - connection : JdbcConnection
          + destroy()
          + init()
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest.TestBug77183StatementInterceptor {
          {static} + countInterceptions : int
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest.TestBug77449QueryInterceptor {
          - sendFracSecs : boolean
          + init()
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest.TestBug77681QueryInterceptor {
          - execCounter : int
          - expected : char[]
          {static} - expectedNonRWBS : char[]
          {static} - expectedRWBS : char[]
          + init()
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest.TestBug81468QueryInterceptor {
          {static} - executionsCount : int
          {static} - expectedNumberOfExecutions : int
          {static} - expectedNumberOfQueries : int
          {static} - expectedNumberOfValues : int
          + preProcess()
          {static} ~ resetExpectedValues()
          - countQueries()
          - countValues()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest.TestBug81706QueryInterceptor {
          {static} + isActive : boolean
          {static} + testCase : String
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest.TestBug84117QueryInterceptor {
          {static} ~ expectsThreadName : boolean
          {static} ~ occurrences : int
          + preProcess()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest.TestBug96623ExceptionInterceptor {
          {static} ~ testCase : String
          + destroy()
          + init()
          + interceptException()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StatementRegressionTest.subTestBug68916ConcurrentTask {
          ~ closeOnCompletionIsOverriden : boolean
          ~ query : String
          ~ testConnection : Connection
          + call()
          ~ subTestBug68916ConcurrentTask()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StressRegressionTest {
          - numThreadsStarted : int
          + testBug114410()
          + testBug67760()
          + testContention()
          + testCreateConnections()
          + testCreateConnectionsUnderLoad()
          ~ contentiousWork()
          ~ reportDone()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StressRegressionTest.BusyThread {
          ~ stop : boolean
          + run()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StressRegressionTest.ContentionThread {
          ~ elapsedTimeMillis : long
          ~ threadConn : Connection
          ~ threadNumber : int
          ~ threadStmt : Statement
          + ContentionThread()
          + run()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StressRegressionTest.CreateThread {
          ~ numConnections : int
          + CreateThread()
          + CreateThread()
          + CreateThread()
          + run()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StressRegressionTest.SharedInfoForTestBug67760 {
          {static} ~ job1Iterations : int
          {static} ~ job2Iterations : int
          {static} ~ prevJob1Iterations : int
          {static} ~ prevJob2Iterations : int
          {static} ~ running : boolean
          {static} ~ iterationsChanged()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.StringRegressionTest {
          + testBase64Decoder()
          + testBug11614()
          + testBug11629()
          + testBug25047()
          + testBug64731()
          + testBug7601()
          + testNewlines()
          - testBase64DecoderItem()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.SubqueriesRegressionTest {
          {static} - REPETITIONS : int
          + setUp()
          + testSubQuery1()
          + testSubQuery2()
          + testSubQuery3()
          + testSubQuery4()
          + testSubQuery5()
          - createTables()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.SyntaxRegressionTest {
          + testAlterTableAlgorithmLock()
          + testCreateTableDataDirectory()
          + testCreateTablespace()
          + testDiscardImportPartitions()
          + testExchangePartition()
          + testExplicitPartitions()
          + testFULLTEXTSearchInnoDB()
          + testGcsReplicationCmds()
          + testGetStackedDiagnostics()
          + testGisFunctions()
          + testHints()
          + testIPv6Functions()
          + testInnodbTablespaceEncryption()
          + testJsonType()
          + testRenameIndex()
          + testSetMergeThreshold()
          + testTableCompression()
          + testTransportableTablespaces()
          + testUserAccountLocking()
          + testUserAccountPwdExpiration()
          - copyFile()
          - testCreateTablespaceCheckTables()
          - testCreateTablespaceCheckTablespaces()
          - testHintsSyntax()
          - testJsonTypeCheckFunction()
          - testSetMergeThresholdIndices()
      }
    }
  }
  

  namespace testsuite {
    namespace regression {
      class testsuite.regression.UtilsRegressionTest {
          + testBug104170()
          + testBug20913114()
          + testBug70436()
          + testBug82115()
          + testTimeZones()
      }
    }
  }
  

  testsuite.regression.CharsetRegressionTest +-down- testsuite.regression.CharsetRegressionTest.Bug71038QueryInterceptor
  testsuite.regression.CharsetRegressionTest +-down- testsuite.regression.CharsetRegressionTest.Bug72712QueryInterceptor
  testsuite.regression.CharsetRegressionTest +-down- testsuite.regression.CharsetRegressionTest.Bug73663QueryInterceptor
  testsuite.regression.CharsetRegressionTest +-down- testsuite.regression.CharsetRegressionTest.Bug95139QueryInterceptor
  testsuite.regression.CharsetRegressionTest +-down- testsuite.regression.CharsetRegressionTest.TestBug64205QueryInterceptor
  testsuite.regression.CharsetRegressionTest +-down- testsuite.regression.CharsetRegressionTest.TestSetNamesQueryInterceptor
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.AuthTestPlugin
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.Bug104067QueryInterceptor
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.Bug29329326QueryInterceptor
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.Bug56100QueryInterceptor
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.Bug75168LoadBalanceExceptionChecker
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.Bug75168QueryInterceptor
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.Bug75592QueryInterceptor
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.Bug88227QueryInterceptor
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.CancelTask
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.CountingReBalanceStrategy
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.ForcedLoadBalanceStrategy
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.PollTask
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.PortNumberSocketFactory
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.TestBug101596Transformer
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.TestBug102404Listener
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.TestBug21934573ExceptionInterceptor
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.TestBug34918989PropTransKO
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.TestBug34918989PropTransOK
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.TestBug35358417Listener
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.TestBug57662Logger
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.TestBug67803ExceptionInterceptor
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.TestBug71850ExceptionInterceptor
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.TestBug73053InputStreamWrapper
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.TestBug73053SocketFactory
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.TestBug73053SocketWrapper
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.TestBug98445ClientInfoProvider
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.ThreadPerTaskExecutor
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.ThreeAttemptsPlugin
  testsuite.regression.ConnectionRegressionTest +-down- testsuite.regression.ConnectionRegressionTest.TwoQuestionsPlugin
  testsuite.regression.ConnectionRegressionTest.AuthTestPlugin .up.|> com.mysql.cj.protocol.AuthenticationPlugin
  testsuite.regression.ConnectionRegressionTest.Bug75168LoadBalanceExceptionChecker .up.|> com.mysql.cj.jdbc.ha.LoadBalanceExceptionChecker
  testsuite.regression.ConnectionRegressionTest.CancelTask .up.|> java.lang.Runnable
  testsuite.regression.ConnectionRegressionTest.CountingReBalanceStrategy -up-|> com.mysql.cj.jdbc.ha.RandomBalanceStrategy
  testsuite.regression.ConnectionRegressionTest.ForcedLoadBalanceStrategy -up-|> com.mysql.cj.jdbc.ha.RandomBalanceStrategy
  testsuite.regression.ConnectionRegressionTest.PollTask .up.|> java.lang.Runnable
  testsuite.regression.ConnectionRegressionTest.PortNumberSocketFactory -up-|> com.mysql.cj.protocol.StandardSocketFactory
  testsuite.regression.ConnectionRegressionTest.TestBug101596Transformer .up.|> com.mysql.cj.conf.ConnectionPropertiesTransform
  testsuite.regression.ConnectionRegressionTest.TestBug102404Listener .up.|> com.mysql.cj.protocol.ServerSessionStateController.SessionStateChangesListener
  testsuite.regression.ConnectionRegressionTest.TestBug21934573ExceptionInterceptor .up.|> com.mysql.cj.exceptions.ExceptionInterceptor
  testsuite.regression.ConnectionRegressionTest.TestBug34918989PropTransOK .up.|> com.mysql.cj.conf.ConnectionPropertiesTransform
  testsuite.regression.ConnectionRegressionTest.TestBug35358417Listener .up.|> com.mysql.cj.protocol.ServerSessionStateController.SessionStateChangesListener
  testsuite.regression.ConnectionRegressionTest.TestBug57662Logger -up-|> com.mysql.cj.log.StandardLogger
  testsuite.regression.ConnectionRegressionTest.TestBug67803ExceptionInterceptor .up.|> com.mysql.cj.exceptions.ExceptionInterceptor
  testsuite.regression.ConnectionRegressionTest.TestBug71850ExceptionInterceptor .up.|> com.mysql.cj.exceptions.ExceptionInterceptor
  testsuite.regression.ConnectionRegressionTest.TestBug73053InputStreamWrapper -up-|> java.io.InputStream
  testsuite.regression.ConnectionRegressionTest.TestBug73053SocketFactory -up-|> com.mysql.cj.protocol.StandardSocketFactory
  testsuite.regression.ConnectionRegressionTest.TestBug73053SocketWrapper -up-|> java.net.Socket
  testsuite.regression.ConnectionRegressionTest.TestBug98445ClientInfoProvider .up.|> com.mysql.cj.jdbc.ClientInfoProvider
  testsuite.regression.ConnectionRegressionTest.ThreadPerTaskExecutor .up.|> java.util.concurrent.Executor
  testsuite.regression.ConnectionRegressionTest.ThreeAttemptsPlugin .up.|> com.mysql.cj.protocol.AuthenticationPlugin
  testsuite.regression.ConnectionRegressionTest.TwoQuestionsPlugin .up.|> com.mysql.cj.protocol.AuthenticationPlugin
  testsuite.regression.MetaDataRegressionTest +-down- testsuite.regression.MetaDataRegressionTest.QueryInterceptorBug61332
  testsuite.regression.MetaDataRegressionTest +-down- testsuite.regression.MetaDataRegressionTest.TestBug97413Columns
  testsuite.regression.NonLocalSocketFactory -up-|> com.mysql.cj.protocol.StandardSocketFactory
  testsuite.regression.PooledConnectionRegressionTest +-down- testsuite.regression.PooledConnectionRegressionTest.ConnectionListener
  testsuite.regression.PooledConnectionRegressionTest.ConnectionListener .up.|> javax.sql.ConnectionEventListener
  testsuite.regression.ResultSetRegressionTest +-down- testsuite.regression.ResultSetRegressionTest.TestBug67318ExceptionInterceptor
  testsuite.regression.ResultSetRegressionTest.TestBug67318ExceptionInterceptor .up.|> com.mysql.cj.exceptions.ExceptionInterceptor
  testsuite.regression.StatementRegressionTest +-down- testsuite.regression.StatementRegressionTest.Bug101389QueryInterceptor
  testsuite.regression.StatementRegressionTest +-down- testsuite.regression.StatementRegressionTest.Bug39426Interceptor
  testsuite.regression.StatementRegressionTest +-down- testsuite.regression.StatementRegressionTest.IsClosedInputStream
  testsuite.regression.StatementRegressionTest +-down- testsuite.regression.StatementRegressionTest.IsClosedReader
  testsuite.regression.StatementRegressionTest +-down- testsuite.regression.StatementRegressionTest.PrepareThread
  testsuite.regression.StatementRegressionTest +-down- testsuite.regression.StatementRegressionTest.QueryInfoQueryInterceptor
  testsuite.regression.StatementRegressionTest +-down- testsuite.regression.StatementRegressionTest.ScanDetectingInterceptor
  testsuite.regression.StatementRegressionTest +-down- testsuite.regression.StatementRegressionTest.TestBug51666QueryInterceptor
  testsuite.regression.StatementRegressionTest +-down- testsuite.regression.StatementRegressionTest.TestBug77183StatementInterceptor
  testsuite.regression.StatementRegressionTest +-down- testsuite.regression.StatementRegressionTest.TestBug77449QueryInterceptor
  testsuite.regression.StatementRegressionTest +-down- testsuite.regression.StatementRegressionTest.TestBug77681QueryInterceptor
  testsuite.regression.StatementRegressionTest +-down- testsuite.regression.StatementRegressionTest.TestBug81468QueryInterceptor
  testsuite.regression.StatementRegressionTest +-down- testsuite.regression.StatementRegressionTest.TestBug81706QueryInterceptor
  testsuite.regression.StatementRegressionTest +-down- testsuite.regression.StatementRegressionTest.TestBug84117QueryInterceptor
  testsuite.regression.StatementRegressionTest +-down- testsuite.regression.StatementRegressionTest.TestBug96623ExceptionInterceptor
  testsuite.regression.StatementRegressionTest +-down- testsuite.regression.StatementRegressionTest.subTestBug68916ConcurrentTask
  testsuite.regression.StatementRegressionTest.IsClosedInputStream -up-|> java.io.ByteArrayInputStream
  testsuite.regression.StatementRegressionTest.IsClosedReader -up-|> java.io.StringReader
  testsuite.regression.StatementRegressionTest.TestBug96623ExceptionInterceptor .up.|> com.mysql.cj.exceptions.ExceptionInterceptor
  testsuite.regression.StatementRegressionTest.subTestBug68916ConcurrentTask .up.|> java.util.concurrent.Callable
  testsuite.regression.StressRegressionTest +-down- testsuite.regression.StressRegressionTest.BusyThread
  testsuite.regression.StressRegressionTest +-down- testsuite.regression.StressRegressionTest.ContentionThread
  testsuite.regression.StressRegressionTest +-down- testsuite.regression.StressRegressionTest.CreateThread
  testsuite.regression.StressRegressionTest +-down- testsuite.regression.StressRegressionTest.SharedInfoForTestBug67760
  testsuite.regression.StressRegressionTest.CreateThread o-- testsuite.regression.StressRegressionTest.BusyThread : busyThread


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
